CI_BUILD_NUMBER ?= $(USER)-snapshot
CI_WORKDIR ?= $(shell pwd)

CI_IVY_CACHE ?= $(HOME)/.ivy2
CI_SBT_CACHE ?= $(HOME)/.sbt

# Artifact information.
VERSION ?= $(CI_BUILD_NUMBER)
PUBLISH_TAG = mup.cr/{{artifactName}}/{{artifactName}}-service:$(CI_BUILD_NUMBER)

CLUSTER ?= sandbox
ZONE ?= us-central1-b

# Run the build in the build container.
package:
	@echo TODO

package-sbt:
	@echo TODO


publish: package
	docker push $(PUBLISH_TAG)

base-tag:
	@echo "mup.cr/blt/java8:80"

version:
	@echo $(VERSION)

deploy-only:
	@echo TODO

publish-tag:
	@echo $(PUBLISH_TAG)

get-credentials:
	echo "Deploying service to $(CLUSTER) cluster in $(ZONE) zone."
	@gcloud container clusters get-credentials $(CLUSTER) --zone $(ZONE)

deploy: get-credentials deploy-only

set-stage:
	$(eval CLUSTER=stage)
	$(eval ZONE=us-east1-b)

set-prod:
	$(eval CLUSTER=prod)
	$(eval ZONE=us-east1-c)

deploy-stage: set-stage deploy

deploy-prod: set-prod deploy
